# Copyright (c) 2018 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.

# travis-ci.org CI unit tests integration configuration file.

language: python

python:
  - "2.7"

# First set up Qt for Python to use it.
install:
  # PySide is tricky to install and run. Let's get a wheel from someone who already compiled it for
  # Travis.
  # Taken from: https://stackoverflow.com/questions/24489588/how-can-i-install-pyside-on-travis
  - sudo apt-get install libqt4-dev
  - pip install PySide==1.2.2 --no-index --find-links https://parkin.github.io/python-wheelhouse/;
  # Travis CI servers use virtualenvs, so we need to finish the install by the following
  - python "~/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/pyside_postinstall.py" -install
  # Now we need to start the X server...
  # Taken from: https://github.com/colmap/colmap/commit/606d3cd09931d78a3272f99b5e7a2cb6894e243e
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Finally, tell Qt to run offscreen.
  - export QT_QPA_PLATFORM=offscreen
  - git clone https://github.com/shotgunsoftware/tk-core /tmp/tk-core --depth 1 --branch master

# command to run tests
script: echo "Success!!"
#after_success: coveralls